global:

  hipchat_auth_token: 'xxx'
  hipchat_api_url: 'https://api.hipchat.com/'

route:
  group_by: [cluster] 
  receiver: team-hipchat
  routes:
  - match:
      severity: hipchat
    receiver: team-hipchat

receivers:
  - name: team-hipchat
    hipchat_configs:
    - auth_token: 'yyy'
      room_id: 12345
      message_format: html
      notify: true
